### ISSUE TITLE
create special branch for rho contractions

### ISSUE THREAD

**Issue by kostrzewa** [HISKP-LQCD/sLapH-contractions#103]
@matfischer @pittlerf 

Could you please create a special branch for the rho contractions based off the commit that is now used for them with proper VdaggerV reading checks in place? This can then be used for the rho stuff until we have found a more general solution to deal with the silly memory load.

**Comment by pittlerf** [comment]
Hi, I just created rho_nf2 branch in my fork.

**Comment by kostrzewa** [comment]
Please create it here instead

**Comment by pittlerf** [comment]
Done
