### ISSUE TITLE
Normalization of correlation functions

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/sLapH-contractions#44]
Bartek suggested that there the `V^\dagger V` objects are not properly normalized, a `1/L^3` factor is missing for each of them. This means that the correlation functions are not properly normalized.

For the GEVP this should not have any effect, but we should still make sure that the normalization is correct.

**Comment by kostrzewa** [comment]
@maowerner @martin-ueding 

So, after https://github.com/HISKP-LQCD/sLapH-contractions/commit/a4f909ef5929fb09d09a2c929d6c29e4ed7e280e#diff-7757c5b9342e11601001841afc6c0133, it seems to me that the individual diagrams have the correct averaging normalisation (division by the number of summands) and there are no hard-coded special factors around. The correlation functions are normalised further by the number of source time slices, which is appropriate.

Beyond that, it seems to me that the normalisation as it is should be correct, in the sense that it will result in a GEVP with the correct relative weights of the various correlation functions.  There are, however, some odd factors of "2" and "3" which I've pointed out.

The absolute volume- and kappa-dependent normalisations would only need to be performed if one wanted to directly compare correlation functions from different volumes with very well matched smearing radii, which we don't want to do at this point in time.

**Comment by maowerner** [comment]
I answered your questions in the inline comments. The short version is:

The commit you looked at is the one where we changed the normalization. These fudge factors where previously wrong where 5 random vectors where hardcoded. We put them in to see whether our tests worked and we understood the discrepancies after redoing the normalization. They were deleted the very next commit

https://github.com/HISKP-LQCD/sLapH-contractions/commit/a96ebbfa5f7317f213b81078668829cf5ff3bf03

**Comment by kostrzewa** [comment]
Indeed, I missed the following commit. Should have checked against the current code :)

**Comment by maowerner** [comment]
Are all normalization coefficients covered or is there still something we need to work out? Otherwise we might close this issue.

**Comment by kostrzewa** [comment]
I think we should be fine.
