### ISSUE TITLE
loop over configs does not end when delta_config == 0

### ISSUE THREAD

**Issue by kostrzewa** [HISKP-LQCD/sLapH-contractions#69]
Perhaps a default of '1' should be set in case the parameter is missing the in global config file.

**Comment by martin-ueding** [comment]
This is indeed a bug, now fixed.

**Comment by martin-ueding** [comment]
Let me try to close this Issue. There seems to be some problem with GitHub permissions perhaps?

**Comment by martin-ueding** [comment]
This makes sense, I have changed that.
