### ISSUE TITLE
L1 in Diagram.cpp can be omitted 

### ISSUE THREAD

**Issue by maowerner** [HISKP-LQCD/sLapH-contractions#72]
L1 contains a map with products of quarklines that might appear again. By sorting quantum_num_ids_ it can just be reused directly.

**Comment by maowerner** [comment]
We now have a "feature branch" for this. The master (again) builds L1/L2. 

This is intended as a hotfix to run the rho contractions on Jurecabooster. If it shall be supported, a compiler flag for this should be passed.

**Comment by kostrzewa** [comment]
Any timings that you can provide? Using less memory will be very useful, but if the cost in terms of time to solution is massive, perhaps we can come up with another solution.

Something that I was thinking of, given the auto-correlation times that we observe, is to not use all source time slices. One could relatively easily randomly sample a subset of source time slices per config.

**Comment by maowerner** [comment]
On Jurecabooster the code does not run with L1 in there. So I cannot do benchmarks there.

On Qbig, the runtime differs wildly with the node I got. I could do a few benchmarks, but I currently have sufficient throughput, so I would rather avoid developing the code.

One thing to test though is whether I can fit a 48 lattice on Jurecabooster.
