### ISSUE TITLE
Add timings into refactored code

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/sLapH-contractions#83]
The timings have been dropped while refactoring, they need to be put back into the new functions.

**Comment by martin-ueding** [comment]
I have added the `LT_DIAGRAMS` timing to the `Diagram::assemble_impl()` function.

@kostrzewa, there were some instances where the `START` as within the loop but the `STOP` and `PRINT` outside of that. Was that intentional to just measure the last iteration?

**Comment by kostrzewa** [comment]
It was probably a bug.
