### ISSUE TITLE
Take required correlators from file

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/sLapH-contractions#85]
The whole setup of lookup tables is the same for each configuration. Therefore it could be computed once and stored to disk. For all other configurations we can just load this and directly start contracting.

Boost has the *serialization* framework which will work great here.

**Comment by martin-ueding** [comment]
I have tried to start contractions for three pions with P² = 4. The building of the dreaded lookup tables takes more than a day, we do not know how long. Since this is neither parallelized nor serialized, the time needed for this is just too great. Likely the problem is because the combinatoric possibilities explode with three particles.

We had discussed to switch the contraction code such that it just computes the correlators that we need. It might be time to actually implement this for the three pion project.

**Comment by martin-ueding** [comment]
Besides doing a lot of redundant work this part of the code actually is grossly inefficient. It just builds the outer product of all momenta and then finds in most cases that it does not conserve momentum. That's just nonsense.

For the 3pi project I have done the analytic projections now, and we do know exactly what correlators we need. Fiddling with the cutoffs was worth a try, but I already consider it failed. I have run in it on B55.32 where the cutoffs have some particular values. So then I have this configuration file:

```ini
momentum_cutoff_0 = 2
momentum_cutoff_1 = 3
momentum_cutoff_2 = 4
momentum_cutoff_3 = 3
momentum_cutoff_4 = 4

[operator_lists]
operator_list = g5.d0.p0,1,2,3,4

[correlator_lists]
correlator_list = C2c:Op0:Q0:Op0:Q0:P0,1,2,3,4

correlator_list = C4cC:Op0:Q0:Op0:Q0:Op0:Q0:Op0:Q0:P0,1,2,3,4
correlator_list = C4cD:Op0:Q0:Op0:Q0:Op0:Q0:Op0:Q0:P0,1,2,3,4

correlator_list = C6cC:Op0:Q0:Op0:Q0:Op0:Q0:Op0:Q0:Op0:Q0:Op0:Q0:P0,1,2,3,4
correlator_list = C6cD:Op0:Q0:Op0:Q0:Op0:Q0:Op0:Q0:Op0:Q0:Op0:Q0:P0,1,2,3,4
correlator_list = C6cCD:Op0:Q0:Op0:Q0:Op0:Q0:Op0:Q0:Op0:Q0:Op0:Q0:P0,1,2,3,4
```

This is running for 59 minutes now and still in the serial part, therefore building the list for C6cCD. And the cutoff for P² = 4 has been 4 all along, so we have not slashed that down. It could very well be that the reduction for P² = 3 with 7 → 3 was not sufficient to take away the cost and it just buries itself in the P² = 4 case. We could try to do the frames separately, but I think this is getting silly really.

So the idea is to just make the code read a flat text file with the HDF5 names that it must produce and then let it build the *lookup tables* from that.

**Comment by kostrzewa** [comment]
> Besides doing a lot of redundant work this part of the code actually is grossly inefficient. It just builds the outer product of all momenta and then finds in most cases that it does not conserve momentum. That's just nonsense.

If it were done just once, it's not a big deal, but the code does it many, many times...

**Comment by martin-ueding** [comment]
When having quarks with momentum squared up to 4, there are 35937 possible combinations at source. It then goes through all of them and checks whether they are below the cutoff. If that is the case then it goes through all 35937 combinations at sink and checks whether they happen to have the same total momentum. So it is not quite the square, 1,291,467,969, but still mind boggling. And it seems that the cutoffs are not even checked at sink! So you could have three particles with momenta squared 1;1;0 get matched up with a 0;0;4 in the P² = 4 case even if you set the sum cutoff to 2. Guess it will produce many more correlators than we actually want.

@maowerner: Is it correct that the momentum-square-sum-cutoff is only enforced at the source but not at the sink?

**Comment by martin-ueding** [comment]
There is one peculiar thing that I noticed. I just tried to do the moving frames one by one and just had these timings:

P² | cutoff | MM:SS
---: | ---: | ---:
0 | 2 | 00:01
1 | 3 | 02:29
2 | 4 | 05:14
3 | 3 | 00:48
4 | 4 | 00:49

But when running all five moving frames at the same time it does not finish in even 2:49:15. I am not sure whether the code produces the desired results if it is split up like that. Either something is missing or the part of the code which does this is so super convoluted that it spends an extreme time building discarded momentum combinations.

In that case it could indeed be easiest to just do it frame by frame and not tweak the code at all.

**Comment by martin-ueding** [comment]
I try to figure out how much of the lookup table population logic I should replace. A minimally invasive approach seems to be most time efficient, so I will see whether that works out.

The expensive part is this function here:

```cpp
void build_quantum_numbers_from_correlator_list(
    Correlators_2 const &correlator,
    Operator_list const &operator_list,
    std::vector<std::vector<QuantumNumbers>> &quantum_numbers,
    std::map<int, int> const &momentum_cutoff);
```

The effect is to set `quantum_numbers`. Now that is just a structure of these here:

```cpp
struct QuantumNumbers {
  using VectorData = Eigen::Vector3i;

  std::vector<int> gamma;
  DisplacementDirection displacement;
  VectorData momentum;
};
```

Well, all that information is available in my flat list of correlation functions. So I think I can do the same task with a more simple function that uses the already generated HDF5 dataset names and works from there.

The information that we have available is also this struct describing the correlator in question:

```cpp
struct Correlators_2 {
  using VectorData = Eigen::Vector3i;

  std::string type;
  std::vector<int> quark_numbers;
  std::vector<int> operator_numbers;
  std::string GEVP;
  std::vector<VectorData> tot_mom;
};
```

So from `type` we know like `C6cC`, `GEVP` eludes me at the moment. The total momentum seems to be a three vector, so apparently we have one such entry for each total momentum. This is not a problem as I could already do a group-by by correlator name and also by total momentum in the preparation of the list of dataset names. It would be JSON instead of plain text, but I can generated that from the output of the analytic projection code straightforwardly.

The `Operator_list` is a structure of `QuantumNumbers`, so we just let the code generate that with given maximum total momenta and then in the expensive function pick out the ones that we really want. This might result in building of VdaggerV that we do not really need, but are these expensive?

Then instead of building the momentum combinations ourselves with the combinatoric inefficiency, we just take the appropriate portion of the given list and just populate it with that. We would still have to check the lists of available operators and use the IDs, but that should scale much better.

We might realize that the actual contractions are too expensive in the end, but I think that this approach is not too much work and could bring us forward. The configuration file would have to be written as usual and then a new *shortcut file* would be added. I mean we could generate everything from the file and not specify anything except quark dilution, but I would like to do it fast first.

**Comment by kostrzewa** [comment]
> There is one peculiar thing that I noticed. I just tried to do the moving frames one by one and just had these timings:

Keep in mind that there are operator cutoffs and correlator cutoffs. Doing a particular moving frame by itself still required having all momenta for the operators available to build all required combinations.

**Comment by kostrzewa** [comment]
> This might result in building of VdaggerV that we do not really need, but are these expensive?

Note overly so but for the large lattices, for example, it makes sense to pre-build them as they still take some tens of thousands of core hours in total (as we have done for the latest rho contractions).

**Comment by martin-ueding** [comment]
> Keep in mind that there are operator cutoffs and correlator cutoffs. Doing a particular moving frame by itself still required having all momenta for the operators available to build all required combinations.

I know, and I have kept the operator momenta the same (`P0,1,2,3,4`) the whole time. Therefore I think that I should get all the combinations that I want. It just baffles me that this is so much faster than doing them all at once.

So I see these ways to go forward:

1. Do the moving frames one by one and just build the VdaggerV on the fly.
2. Same, but pre-generate the VdaggerV. What code do we use for that? The executable that is branched off from the contraction code?
3. Read in the desired correlators as planned.
4. Figure out why the current momentum combination generation code is so damn slow when one does multiple moving frames at a time.

**Comment by kostrzewa** [comment]
> I know, and I have kept the operator momenta the same (P0,1,2,3,4) the whole time. Therefore I think that I should get all the combinations that I want. It just baffles me that this is so much faster than doing them all at once.

Then I'm also perplexed...

**Comment by martin-ueding** [comment]
Using `h5ls` I have extracted the names that are available in the file:

```
$ wc -l C40C_all.txt 
254 C40C_all.txt
```

Then I have run the moving frames separately in the test case for one of the diagrams and looked at the ones that are there:

```
$ wc -l C40C_P?.txt
   98 C40C_P0.txt
   48 C40C_P1.txt
   96 C40C_P2.txt
    0 C40C_P3.txt
   12 C40C_P4.txt
  254 insgesamt
```

We can see that the total number is there. For some reason there are no P² = 3 correlators generated, I guess that just does not work out with the cutoffs that are in place. And it is not just the numbers, everything is there, nothing is duplicate:

```
$ sort C40C_all.txt > C40C_all_sort.txt
$ sort C40C_P?.txt > C40C_sep_sort.txt
$ diff -u C40C_all_sort.txt C40C_sep_sort.txt
(no output)
```

So it seems that the performance of that piece of code is dodgy, but we can just run them separately and not worry about that section until production is started.

**Comment by martin-ueding** [comment]
I have created a Python script that takes the prescription JSON files and extracts a list of unique correlators and groups them by diagram like this:

```js
{
  "C6cC": [
    "C6cC_uuuuuu_p-1-1-1.d000.g5_p-1-10.d000.g5_p010.d000.g5_p100.d000.g5_p010.d000.g5_p101.d000.g5",
    "C6cC_uuuuuu_p-1-1-1.d000.g5_p-1-10.d000.g5_p010.d000.g5_p101.d000.g5_p010.d000.g5_p100.d000.g5",
…
```

I will throw out the complete kinematics portion of the code and just read in that list. If one wants to do rho contractions once can just extract the list from the existing correlators and use that. We won't lose capability this way. Alternatively one could go back to version `v2.1.0`.

**Comment by martin-ueding** [comment]
Yesterday I have worked a couple hours intensively on understanding the various data structures and started adapting the code. Today I just did the final touches and now I have this here:

```
Test project /home/mu/Build/sLapH-contractions/Release
    Start 1: integration_L4_all_diagrams
1/1 Test #1: integration_L4_all_diagrams ......   Passed   10.56 sec
```

![serveimage](https://user-images.githubusercontent.com/976924/67000137-8914fe00-f0d7-11e9-830c-7758fb9940ea.png)

I'll see about the other tests, but it seems that the change was not that hard after all! My lesson is that it is much more productive to just ignore that this will set back production by a bit and then it was finished surprisingly quickly!

**Comment by kostrzewa** [comment]
:)

**Comment by kostrzewa** [comment]
> My lesson is that it is much more productive to just ignore that this will set back production by a bit and then it was finished surprisingly quickly!

That has been my experience as well, if one has the necessary headspace for an intense session.

**Comment by martin-ueding** [comment]
I've been in a more stressed-out headspace and therefore did not get anything done. And yesterday I was just in it and here we go, all tests passed. I will try it out with the 3pi list and see whether that now works on JUWELS.
