### ISSUE TITLE
New timing mechanism

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/sLapH-contractions#94]
Timing this code with sampling profilers like gprof or perf turns out to be very useless because the call hierarchy somehow gets lost or severely damaged. Additionally it does not extract runtime information like the currently handled diagram (a `std::string`). Bartek has implemented timings, but it does not persist the hierarchy of calls, making it hard to extract insights of.

I'd like to upgrade the timings in the code such that we obtain the hierarchy and can generate a graph just like the ones that I can with gprof and gprof2dot. For this I will need to know the time that is spend within the function and which functions were called.

For this I consider something very similar to the XML generating facility in Chroma. The output would perhaps be the following:

```xml
<call function="…" info="…">
  <call function="…" info="…">
    …
    <total time="…" />
  </call>
  …
  <total time="…" />
</call>
```

This will give us the hierarchy. We can sum up the total time of the children and subtract that from the parent's total time and get the self time. We can count the number of calls for a given function. And we can tally all the calls to a different function and group by the `info` attribute. Instead of a general free text `info` attribute one could also just add whatever makes sense, like time slices and diagram name.

The advantage of XML is that it can be emitted line by line, there is no need to store anything in memory. XML libraries with XPath make working with XML rather straightforward in any programming language. I'd write the analysis in Python.

On the C++ side I would implement a `Timings` class which has a `void push(std::string function, std::string info)` and a `pop()` method. The `push` will start the time and emit the `<call>` tag. Then in `pop()` it will stop the timer, emit the `<total />` tag and the `</call>` tag. Then I'd create a `TimingScope` class which just calls `push` in the ctor and `pop` in the dtor, like `std::lock_guard` for instance. This way one just have to add one line at the beginning of each function to get the timings on that level.

In order to control the granularity there will be a `template <int level>` for the `push` and `pop` functions and also for the `TimingScope` class. This way we can use a `if constexpr` to conditionally enable the body of the `push` and `pop` functions depending on a granularity setting from CMake.

Each thread will emit its timings into a separate XML file such that they do not interfere with each other. In the end one can either just look at one of the XML files or try to merge them.

---

Perhaps one can refine the design slightly. We do not want to open the streams all the time. Therefore I would use a singleton which resolves the correct stream via `omp_get_thread_num()`. Then one would only need the `TimingScope` which has a ctor with `function` and `info`. The dtor stops the measurement and emits the closing tag. This is not really nice because the dtor must not throw, but it should not throw anyway.

I believe that this should already be it.

**Comment by martin-ueding** [comment]
I have an implementation now and the following test program:

```cpp
#include <timings.hpp>

void foo();
void bar();
void baz();

void foo() {
  TimingScope<2> timing_scope("foo", "");

  bar();
  baz();
}

void bar() {
  TimingScope<2> timing_scope("bar", "");

  baz();
}

void baz() {
  TimingScope<3> timing_scope("baz", "");
}

int main() {
  TimingScope<1> timing_scope("main", "");

  foo();
  bar();
}
```

The generated XML looks like this:

```xml
<timings>
  <call function='main' info=''>
    <call function='foo' info=''>
      <call function='bar' info=''>
        <call function='baz' info=''>
          <total time='4.03001e-07' />
        </call>
        <total time='1.7955e-05' />
      </call>
      <call function='baz' info=''>
        <total time='4.54002e-07' />
      </call>
      <total time='2.2443e-05' />
    </call>
    <call function='bar' info=''>
      <call function='baz' info=''>
        <total time='2.58002e-07' />
      </call>
      <total time='1.899e-06' />
    </call>
    <total time='0.00019495' />
  </call>
</timings>
```

Now I need to think about how to analyze this data and present it in graph form.

**Comment by martin-ueding** [comment]
The graph that is generated by gprof2dot looks like this:

![Auswahl_062](https://user-images.githubusercontent.com/976924/57911157-44b2d700-7887-11e9-8b1a-616fd5c081e1.png)

In each vertex we can see the following:

- Function name (C++ template parameters and arguments are stripped here)
- Cumulative time as a percentage of total runtime
- Self time
- Number of calls

On the edges we see the cumulative time spend in this children by that function and the number of calls.

We can extract the same information from the above XML profile. I just have to accumulate it recursively into vertices and edges and dump all that into a file for GraphViz to visualize. This works well with a Python script and produces this output:

![Auswahl_063](https://user-images.githubusercontent.com/976924/57915710-a5dfa800-7891-11e9-8e56-41ed45d8b86f.png)

When we add some *info* attributes to the timings, we get a more detailed profile. I have performed more function calls, so it is not just exactly the same as above.

![Auswahl_064](https://user-images.githubusercontent.com/976924/57915988-42a24580-7892-11e9-8eff-85a7d3fae22b.png)

Apart from the missing coloring I think that this is going into the right direction.

**Comment by kostrzewa** [comment]
Just a question about your gprof profile, why is the gauge field loaded?

**Comment by kostrzewa** [comment]
Your generated profile graph looks excellent, btw.

**Comment by martin-ueding** [comment]
I did one round of replacing the previous timings with the new hierarchical timings. This is the graph that I get when letting the test case run:

![profile](https://user-images.githubusercontent.com/976924/57921757-6f5c5a00-789e-11e9-8c8b-c883d340104f.png)

Even though this just runs for two seconds, the Python script needs six to parse the 17 MB of XML generated. Even with just a 4⁴ lattice, there are already many calls:

```
Found 133722 calls.
Gathered 133722 vertices and 133721 edges.
Grouped vertices down to 50.
Grouped edges down to 58.
Generated graph.
Wrote graph.
Compiled graph.
```

Now I have to think about the usefulness of this particular profile and whether we learn what we need.

**Comment by martin-ueding** [comment]
@kostrzewa:

> Just a question about your gprof profile, why is the gauge field loaded?

I don't get it. In the parameter file the path to the gauges is not even specified. Therefore it could not even load it. It would be needed for displacements, which we are not using. I just think that gprof gets mightily confused with Eigen.

> Your generated profile graph looks excellent, btw.

Thanks 😃

But I copied the ideas from gprof2dot 😉

**Comment by kostrzewa** [comment]
> Even though this just runs for two seconds, the Python script needs six to parse the 17 MB of XML generated. Even with just a 4⁴ lattice, there are already many calls:

Yes, this was to be expected. I think it is imperative that ```resolve_request``` propagates which diagram it was called from for the profile to be useful.

As for the lowest level, this confirms my measurements from way back when: runtime is basically dominated by ```factor_to_trace``` and, to a lesser extent, by the multiplication operator.

**Comment by kostrzewa** [comment]
To judge how efficient the different parts are, one would have to count flops in the multiplication operator and ```factor_to_trace```.

**Comment by martin-ueding** [comment]
I have just measured the cost of `omp_get_wtime` with this benchmark program:

```cpp
  volatile double time;

  for (auto _ : state) {
    time = omp_get_wtime();
  }
```

It seems to be rather cheap:

```
2019-05-17 13:32:22
Running ./bench-main
Run on (4 X 3200 MHz CPU s)
CPU Caches:
  L1 Data 32K (x2)
  L1 Instruction 32K (x2)
  L2 Unified 256K (x2)
  L3 Unified 3072K (x1)
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
----------------------------------------------------
Benchmark             Time           CPU Iterations
----------------------------------------------------
BM_omp_wtime         30 ns         30 ns   23179416
```

The writing of the XML likely is much more expensive there.

> I think it is imperative that `resolve_request` propagates which diagram it was called from for the profile to be useful.

We do not have to do that in the program, the hierarchy in the profile contains this information already. We would just have to propagate the *info* down within the tree. This way the different nodes are created for the same function. This however might mean that there are no merges down the tree, it might become a mess.

One could just make this exception for `factor_to_trace`. Don't we kind of already see which diagrams contribute via the marked information?

![Auswahl_065](https://user-images.githubusercontent.com/976924/57925763-a3894800-78a9-11e9-9006-0869af725215.png)

One cannot distinguish the C40B (box) and C40C (cross) from each other. And the tr(Q1Q1) are used in various things. So perhaps this is really useful. In the following the *info* attribute is merged down the tree. As I specify the diagram on three layers, this is now a bit redundant, but does not hurt.

![profile](https://user-images.githubusercontent.com/976924/57927399-2b715100-78ae-11e9-9863-baa3fde6a8a3.png)

Is this what you had in mind, @kostrzewa?

**Comment by martin-ueding** [comment]
I've added a square root function to the coloring, now one can better differentiate small times from each other by color. Also redundant *info* entries are collapsed.

![profile](https://user-images.githubusercontent.com/976924/57927911-b4d55300-78af-11e9-8fe6-c4c6fe9362d3.png)

**Comment by martin-ueding** [comment]
For the 4⁴ case I generated 17 MB of XML data, the parsing took 20 s and used 340 MB of memory. For the 24³×48 lattice I generated 16 GB of XML data, and it will take more than 160 GB of memory to process (no surprise there).

I guess I need to figure out a better way of traversing the tree without holding everything in memory. Instead of just generating everything and then accumulating I need to accumulate right away. This will take a bit.

**Comment by martin-ueding** [comment]
As the `xml.etree.ElementTree` from the standard library does not support retrieving parent elements I have switched to the third party `lxml` library. I have just tested that starting up my program without it doing anything already takes 25 MB of memory, I presume from all the libraries that I load. Now just reading the 17 MB XML file will give use 215 MB usage. I expect this to scale linear with the size of the XML file because the hierarchy does not get deeper, it will be just more nodes. It seems that we need 340 GB of memory in order to process this file.

I have put it into the queue on QBIG, but we will have to find a better way of parsing or just reduce the output level. As a first start I have removed the measurement of the right side in `factor_to_trace` as this generated the most entries.

**Comment by kostrzewa** [comment]
Excellent!

One way to save memory would be to actually store the various elements of the hierarchy in a directory hierarchy in many files. That way, one could loop over the branches, loading just a single file relevant for generating the accumulated leaf value in this branch / at this level.

Of course, this means essentially giving up XML as an input format, although the accumulated leaves can still be emitted as XML and then graphed using your existing tools.

**Comment by martin-ueding** [comment]
I have declared the timings for the *right side* as being level 5 and just ran the code with level 4 of timings. This way the output shrunk from 18 GB to a mere 20 MB. Processing this was quick and gives the following profile with the actual current use case for off-diagonal time slice combination:

![prof-4-qbig](https://user-images.githubusercontent.com/976924/58012097-fa825d80-7af3-11e9-8937-034da27a8310.png)

We learn that the `factor_to_trace` takes some time, but virtually all the time is spent in `operator*(std::vector<DilutedFactor>, std::vector<DilutedFactor>)`. There is an excruciating number of calls made to that function. For me this clearly means that we dearly need the “M1-M2/L1-L2” optimization for the C6cC diagram and reuse partial products.

**Comment by kostrzewa** [comment]
Very good!

**Comment by martin-ueding** [comment]
> One way to save memory would be to actually store the various elements of the hierarchy in a directory hierarchy in many files. That way, one could loop over the branches, loading just a single file relevant for generating the accumulated leaf value in this branch / at this level.

I think I see where you are going with this. The order of the calls would likely get lost by this.

But I just realized that we could directly accumulate in the C++ code? So instead of emitting XML we build the hierarchy in memory with some library, Boost has trees that can be serialized as XML. Instead of having one tag per call we would just have unique tags and tally the spend time as we go. This would require that the singleton keeps track of the nesting level in the current thread, but that should be doable. Unless we decide to parse the current XML in other ways, having just the accumulated data sounds sufficient to me.

**Comment by martin-ueding** [comment]
I just wondered why the C6 diagram uses a `DilutedTrace2Factory`, but that was just a copy-paste error, it should be `DilutedTrace6Factory` of course.

**Comment by kostrzewa** [comment]
> I think I see where you are going with this. The order of the calls would likely get lost by this.

Not necessarily, storing the caller in the callee would preserve this, right?

**Comment by martin-ueding** [comment]
I rather meant that the temporal order of calls would get lost this way. But aggregation loses this property anyway. I think having a directory hierarchy with callers and files with times would retain all the information that we desire. But if I work on this again, I'd just aggregate right in this mechanism and not write out a million files only to aggregate later.

**Comment by kostrzewa** [comment]
This all looks very good now. I think we can remove the "LT" timing infrastructure, I would just ask for the creation of the XML files to be suppressed if no timings are to be performed.

**Comment by kostrzewa** [comment]
ping

**Comment by martin-ueding** [comment]
I have started to finish this up in 492cf16a4f6f73760e1fc9a481337f81799f2f9f. Now it should not create timing files unless one specifies the timing level to be greater than zero.
