### ISSUE TITLE
Reincarnation of the M1M2/L1L2 optimization

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/sLapH-contractions#96]
As discussed in the group seminar the C6cC diagram is mightily inefficient because the product of six Q factors (Q2 × Q0 × Q2 × Q0 × Q2 × Q0) is not aggregated in some sensible form but rather re-done for each possible term. This means that we re-do a lot of multiplications redundantly. In the C4cC and C4cB diagrams this was implemented with the M1M2/L1L2 intermediate products. The factors contain Dirac structure and momenta at vertices (denoted as circles) and perambulators (denoted as lines), of interest are the Q0 and the Q2:

![Auswahl_075](https://user-images.githubusercontent.com/976924/58037153-148c6200-7b2d-11e9-9233-2aaf3bcdaefb.png)

We can decompose a diagram like C4cB into such factors:

![Auswahl_072](https://user-images.githubusercontent.com/976924/58036838-510b8e00-7b2c-11e9-8402-2cf390acd7ab.png)

The optimization would basically just put parentheses around the first two and the last two factors such that we get Q2Q0 objects like these:

![Auswahl_073](https://user-images.githubusercontent.com/976924/58036839-510b8e00-7b2c-11e9-96bc-d62456427a79.png)

Of course there are more of them as there are Q2 and Q0 alone. But having these intermediate products as new factors then allowed just a single product between those with reuse of the intermediate terms. These intermediate terms have been called L1 and L2 in this diagram and M1 and M2 in the box diagram. I propose to just call them Q2Q0 in analogy to the tr(Q0Q2), just without the trace.

This optimization was thrown out when the code was generalized to arbitrary many particles. The C6cC diagram turns out to be the most expensive one, and as discussed today the diagram can also be decomposed into these factors:

![Auswahl_074](https://user-images.githubusercontent.com/976924/58036840-510b8e00-7b2c-11e9-8dea-ad3cc29929e3.png)

It might not be perfect and a full dependency graph treatment might give a bit more efficiency. For the case at hand at least it will likely give large saving. I will implement this with the same factory/lazy evaluation mechanism as the other parts are already done. This way these intermediate products can also used in the C4cB diagram, giving even more synergy effects.

**Comment by martin-ueding** [comment]
The removal of the optimizations happened in dc00ce370f3310602c6e61b16057c1617bb38582. I now want to use the `multiply` function again to create these products and then put these into the `DiagramParts` cache as well.

**Comment by martin-ueding** [comment]
I have implemented it, but the results differ from before, even with all operators at zero momentum. I need to have another go at it.

**Comment by martin-ueding** [comment]
Turned out that the optimization was not cut out from the C4cC and C4cB diagrams, the optimization was ported to the 4-Q traces as well. I have just converted this trace to the new cache in d6de766a413ec04338c91e766aad225039ad1ee3 and it does not break the diagrams. This means that the 2-Q cache works and I just did something wrong in the C6cC diagram.

**Comment by martin-ueding** [comment]
I have the factors `f` and the intermediate products `l`. For some reason the original line works (first one). Then the second one also works where I have replaced two factors with a product. But the other two do not work out:

```cpp
    Tr[time_key][i] = factor_to_trace(f0 * f1 * f2 * f3 * f4, f5);
    Tr[time_key][i] = factor_to_trace(l01 * f2 * f3 * f4, f5);
    // Tr[time_key][i] = factor_to_trace(l01 * l23 * f4, f5);
    // Tr[time_key][i] = factor_to_trace(l01 * l23, l45);
```

Also moving the comma in this expression yields wrong results, which it absolutely should not as far as I can think. So it might take a bit more time to figure this out.

The last propagator contains a strange quark as we only have five random vectors per flavor. But that should only affect `f5` and therefore the third line should still work fine.

**Comment by martin-ueding** [comment]
I have just added a second integration test that uses Bartek's new perambulators with up to 10 random vectors. This way I can run the test using only light quarks for the six point diagram. The error is the same, though. So there is something fundamentally broken and it has nothing to do with the strange quark being used for that quark line.

I will have to investigate this further as I currently do not see why that should not work.

**Comment by martin-ueding** [comment]
I get the impression that the interplay of `operator*` and `factor_to_trace` is weird. The following also gives a *different result*:

```cpp
Tr[time_key][i] = factor_to_trace(f0 * f1 * f2 * f3, f4 * f5);
```

This should not be, just as it should not be that only replacing the first terms works but everything else does not.

I can show that the `operator*` violates associativity. The following two lines do not give the same results:

```cpp
Tr[time_key][i] = factor_to_trace((f0 * f1) * f2 * f3 * f4, f5);
Tr[time_key][i] = factor_to_trace(f0 * (f1 * f2) * f3 * f4, f5);
```

Okay, this is a step forward because I think that `factor_to_trace` is then independent of that. I will start writing a unit test or so for this associativity.

**Comment by martin-ueding** [comment]
The test case clearly shows that something is wrong.

```cpp
TEST(DilutedFactor, associativity) {
  auto df1 = make_random_diluted_factor(1);
  auto df2 = make_random_diluted_factor(2);
  auto df3 = make_random_diluted_factor(3);

  EXPECT_NE(df1, df2);
  EXPECT_NE(df1, df3);
  EXPECT_NE(df2, df3);

  auto prod_12_3 = (df1 * df2) * df3;
  auto prod_1_23 = df1 * (df2 * df3);

  std::sort(std::begin(prod_12_3), std::end(prod_12_3));
  std::sort(std::begin(prod_1_23), std::end(prod_1_23));

  EXPECT_EQ(prod_12_3, prod_1_23);
}
```

```
[ RUN      ] DilutedFactor.associativity
/home/mu/Lattice/Code/sLapH-contractions/tests/gtest/associativity.cpp:98: Failure
Expected equality of these values:
  prod_12_3
    Which is: { DilutedFactor{{(0.00910238,0), (0.0298924,0); (0.027502,0), (0.053996,0)}, {8, 16}, 258}, DilutedFactor{{(0.177193,0), (0.944639,0); (0.0987002,0), (0.522917,0)}, {2, 8}, 16}, DilutedFactor{{(0.317508,0), (0.903512,0); (0.173872,0), (0.508794,0)}, {2, 1}, 16}, DilutedFactor{{(0.251019,0), (1.30936,0); (0.121155,0), (0.628117,0)}, {2, 8}, 16}, DilutedFactor{{(0.423408,0), (1.32873,0); (0.200835,0), (0.647832,0)}, {2, 1}, 16}, DilutedFactor{{(0.676233,0), (0.431682,0); (0.420851,0), (0.269526,0)}, {16, 1}, 256}, DilutedFactor{{(0.0872383,0), (0.717445,0); (0.0753941,0), (0.501053,0)}, {16, 2}, 2}, DilutedFactor{{(0.108759,0), (1.01442,0); (0.0504389,0), (0.558015,0)}, {16, 2}, 2}, DilutedFactor{{(0.964207,0), (0.56498,0); (0.679852,0), (0.406564,0)}, {16, 1}, 256}, DilutedFactor{{(0.00293862,0), (0.0311017,0); (0.00811535,0), (0.0625655,0)}, {8, 2}, 258}, DilutedFactor{{(0.187806,0), (0.605501,0); (0.120666,0), (0.396983,0)}, {8, 16}, 2}, DilutedFactor{{(0.149762,0), (0.785679,0); (0.168703,0), (0.90288,0)}, {2, 8}, 16}, DilutedFactor{{(0.256721,0), (0.785141,0); (0.305501,0), (0.854288,0)}, {2, 1}, 16}, DilutedFactor{{(0.139448,0), (0.712378,0); (0.259039,0), (1.35534,0)}, {2, 8}, 16}, DilutedFactor{{(0.221486,0), (0.763524,0); (0.440721,0), (1.36418,0)}, {2, 1}, 16}, DilutedFactor{{(0.00722485,0), (0.0605014,0); (0.00992578,0), (0.0821549,0)}, {4, 2}, 258}, DilutedFactor{{(0.0239975,0), (0.0539488,0); (0.0330664,0), (0.0729364,0)}, {4, 16}, 258}, DilutedFactor{{(0.0758382,0), (0.530391,0); (0.0509803,0), (0.352094,0)}, {8, 2}, 2}, DilutedFactor{{(0.26251,0), (0.438137,0); (0.176917,0), (0.289082,0)}, {8, 16}, 2}, DilutedFactor{{(0.0603948,0), (0.631975,0); (0.0389708,0), (0.412917,0)}, {8, 2}, 2} }
  prod_1_23
    Which is: { DilutedFactor{{(0.149762,0), (0.785679,0); (0.168703,0), (0.90288,0)}, {2, 8}, 16}, DilutedFactor{{(0.177193,0), (0.944639,0); (0.0987002,0), (0.522917,0)}, {2, 8}, 16}, DilutedFactor{{(0.317508,0), (0.903512,0); (0.173872,0), (0.508794,0)}, {2, 1}, 16}, DilutedFactor{{(0.251019,0), (1.30936,0); (0.121155,0), (0.628117,0)}, {2, 8}, 16}, DilutedFactor{{(0.423408,0), (1.32873,0); (0.200835,0), (0.647832,0)}, {2, 1}, 16}, DilutedFactor{{(0.676233,0), (0.431682,0); (0.420851,0), (0.269526,0)}, {16, 1}, 256}, DilutedFactor{{(0.0872383,0), (0.717445,0); (0.0753941,0), (0.501053,0)}, {16, 2}, 2}, DilutedFactor{{(0.108759,0), (1.01442,0); (0.0504389,0), (0.558015,0)}, {16, 2}, 2}, DilutedFactor{{(0.964207,0), (0.56498,0); (0.679852,0), (0.406564,0)}, {16, 1}, 256}, DilutedFactor{{(0.00293862,0), (0.0311017,0); (0.00811535,0), (0.0625655,0)}, {8, 2}, 258}, DilutedFactor{{(0.00910238,0), (0.0298924,0); (0.027502,0), (0.053996,0)}, {8, 16}, 258}, DilutedFactor{{(0.717886,0), (0.427079,0); (0.476845,0), (0.284039,0)}, {8, 1}, 256}, DilutedFactor{{(0.256721,0), (0.785141,0); (0.305501,0), (0.854288,0)}, {2, 1}, 16}, DilutedFactor{{(0.139448,0), (0.712378,0); (0.259039,0), (1.35534,0)}, {2, 8}, 16}, DilutedFactor{{(0.221486,0), (0.763524,0); (0.440721,0), (1.36418,0)}, {2, 1}, 16}, DilutedFactor{{(0.128047,0), (0.665068,0); (0.140676,0), (0.719618,0)}, {16, 8}, 4}, DilutedFactor{{(0.213377,0), (0.682615,0); (0.22432,0), (0.768612,0)}, {16, 1}, 4}, DilutedFactor{{(0.00722485,0), (0.0605014,0); (0.00992578,0), (0.0821549,0)}, {4, 2}, 258}, DilutedFactor{{(0.0239975,0), (0.0539488,0); (0.0330664,0), (0.0729364,0)}, {4, 16}, 258}, DilutedFactor{{(0.459604,0), (0.294077,0); (0.302843,0), (0.193815,0)}, {8, 1}, 256}, DilutedFactor{{(0.0758382,0), (0.530391,0); (0.0509803,0), (0.352094,0)}, {8, 2}, 2}, DilutedFactor{{(0.0603948,0), (0.631975,0); (0.0389708,0), (0.412917,0)}, {8, 2}, 2} }
[  FAILED  ] DilutedFactor.associativity (0 ms)
```

Now that we have a failing test we can work on `operator*`.

**Comment by martin-ueding** [comment]
I am just really uneasy with the fact that the integration tests did not fail up to this point. Somehow we have never triggered that violation of associativity it seems?

**Comment by martin-ueding** [comment]
I have now just taken five random elements per factor in the product. It seems that the resulting products are not even the same length!

```
Expected equality of these values:
  ssize(prod_12_3)
    Which is: 3
  ssize(prod_1_23)
    Which is: 4
```

And they do differ, but not completely.

```
Expected equality of these values:
  prod_12_3
    Which is: { DilutedFactor{{(0.0239975,0), (0.0539488,0); (0.0330664,0), (0.0729364,0)}, {4, 16}, 258}, DilutedFactor{{(0.00722485,0), (0.0605014,0); (0.00992578,0), (0.0821549,0)}, {4, 2}, 258}, DilutedFactor{{(0.221486,0), (0.763524,0); (0.440721,0), (1.36418,0)}, {2, 1}, 16} }
  prod_1_23
    Which is: { DilutedFactor{{(0.0239975,0), (0.0539488,0); (0.0330664,0), (0.0729364,0)}, {4, 16}, 258}, DilutedFactor{{(0.00722485,0), (0.0605014,0); (0.00992578,0), (0.0821549,0)}, {4, 2}, 258}, DilutedFactor{{(0.213377,0), (0.682615,0); (0.22432,0), (0.768612,0)}, {16, 1}, 4}, DilutedFactor{{(0.221486,0), (0.763524,0); (0.440721,0), (1.36418,0)}, {2, 1}, 16} }
```

**Comment by martin-ueding** [comment]
I had discussed that with Bartek. We stumbled on the condition that treats the different random indices.  In the `operator*` I have tried to change this in order to also compute the “diagonal” elements.

```diff
--- a/src/DilutedFactor.cpp
+++ b/src/DilutedFactor.cpp
@@ -18,8 +18,7 @@ std::vector<DilutedFactor> operator*(std::vector<DilutedFactor> const &left_vec,
     for (auto const &right : right_vec) {
       // We want to make the inner and outer indices differ. The inner indices need to
       // match because the product would not make sense otherwise.
-      bool const is_allowed =
-          inner_rnd_id == right.ric.first && left.ric.first != right.ric.second;
+      bool const is_allowed = inner_rnd_id == right.ric.first;
       if (!is_allowed) {
         continue;
       }
```

This makes the unit test pass but then we fail the integration tests for all diagrams that use the M/L optimization:

> No differences found in:
> 
>   - C1_cnfg1000.h5
>   - C20_cnfg1000.h5
>   - C20V_cnfg1000.h5
>   - C2c_cnfg1000.h5
>   - C30_cnfg1000.h5
>   - C30V_cnfg1000.h5
>   - C3c_cnfg1000.h5
>   - C40D_cnfg1000.h5
>   - C40V_cnfg1000.h5
>   - C4cD_cnfg1000.h5
>   - C4cV_cnfg1000.h5
>   - C6cD_cnfg1000.h5
> 
> Differences found in:
> 
>   - C40B_cnfg1000.h5
>   - C40C_cnfg1000.h5
>   - C4cB_cnfg1000.h5
>   - C4cC_cnfg1000.h5
>   - C6cC_cnfg1000.h5
>   - C6cCD_cnfg1000.h5

That can't be the solution as the differences are of the order of 100%:

```
position        C6cCD_uuuuus_p100.d000.g5_p100.d000.g5_p000.d000.g5_p000.d000.g5_p-100.d000.g5_p-100.d000.g5 C6cCD_uuuuus_p100.d000.g5_p100.d000.g5_p000.d000.g5_p000.d000.g5_p-100.d000.g5_p-100.d000.g5 difference          
------------------------------------------------------------
[ 0 ]          -0.000146526    -9.93307e-05    4.71951e-05    
[ 0 ]          0.000133679     9.68855e-05     3.6794e-05     
[ 1 ]          -5.00861e-06    2.48586e-06     7.49446e-06    
[ 1 ]          1.82446e-05     2.84372e-05     1.01926e-05    
[ 3 ]          3.78071e-05     1.31041e-05     2.4703e-05     
[ 3 ]          9.54006e-06     5.55104e-06     3.98903e-06
```

**Comment by martin-ueding** [comment]
We have a problem in the sense that the code might have been doing the wrong thing all along. In the C6cC diagram we basically compute tr(QQQQQQ), which we implement as `tr(Q * Q * Q * Q * Q, Q)` where the `*` only produces products that have different random vector indices left and right and the `tr` forms a last product but only with same indices on left and right. Now we want to rewrite this as `tr((Q * Q) * (Q * Q), (Q * Q))` and cache the `(Q * Q)` objects. The first milestone was to make `*` actually associative. Now the unit test for that works out.

However, the integration test fails and we have sizable deviations from the reference results. The associativity works, I can group like I want and still get the same result which differs from the reference. So I went back to the uncached `tr(Q * Q * Q * Q * Q, Q)` and took a look at the terms that are in the Q⁵. With the old `operator*` I get 6400 terms. Using the following code I have just dumped them to the console.

```cpp
    auto const &p1 = f0 * f1 * f2 * f3 * f4;

#pragma omp master
    {
      for (auto const &elem : p1) {
        std::cout << elem << "\n";
      }
      exit(0);
    }
```

We just need to look at a single one to get a chill:

```
1: DilutedFactor{some matrix, {9, 4}, {3, 4}}
```

The notation is to be read as following: This term has *some matrix* of data. Then it has left and right open random vector indices 9 and 4 (we run with 5 light and 5 strange random vectors here) and then it has 3 and 4 used up internally. The data structure keeps track of the internally used ones in a bit field, so it only tracks unique ones. One would expect four internal indices here because we did five multiplications. So indices have been used multiple times internally, which should be forbidden.

Also we have cases where the outer indices are 6 and 0 but 0, 1, 2 are used internally. That must not happen either.

Applying the new stricter rules in `operator*` these terms seem to drop out like they should. However the result is then different from the reference but independent of the grouping of terms, so association now works.

Keep in mind that only the C6cC is affected but pretty much all diagrams use the `operator*` and the `tr(Q * …, Q)` operation.

Basically there are three options now:

1. The integration tests were doing just fine, we have never broken the code until now. Somehow we still got the right result for the four point diagrams with the obviously forbidden terms going into the six point trace. Fixing the `operator*` to the best of my knowledge was actually a mistake and I broke it.

2. At some point we have broken the code during the refactoring and introduced this dependence that somehow has never surfaced for the four point diagrams but gets us in trouble for the six point diagrams now.

3. The reference result for the six point diagram is just wrong.

Calling the reference for the C6cC wrong is what I would gravitate towards because the diagrams only containing two, three and four point traces are not affected in any way. Given that these strange terms are there, the reference looks fishy. I am just hesitant of doing so because perhaps there is something larger that I am not seeing yet.

If that is the case then my contractions going on on QBIG right now all produce the wrong C6cC.

What do you think of this @kostrzewa: I try to do the cross check with Liuming's data for the zero momentum case and see whether either of my two options agrees with her data. I'm inclined to trust my new code, but I still feel uneasy about this.

**Comment by kostrzewa** [comment]
I agree with your assessment. It would be nice to know why the 2, 3 and 4pt diagrams were invariant under this bug despite the product of three factors giving incorrect contributions. However, it's not strictly necessary to proceed, I'd say. Since you've used the new set of perambulators with 10 random vectors as a reference, this makes me reasonably confident that the rho contractions, for example, are fine.

Would still be nice to have a cross-check of a real set of rho contraction on some 24c48 lattice against Markus's data, just to make doubly sure that nothing has changed.

At some later point then, it will be nice to know what of speedup you achieved, simply to have an idea of how we stand resource-wise.

As for the jobs running on QBIG... well...

**Comment by martin-ueding** [comment]
The reason that this has not been merged in is memory consumption. But the M/L optimization has been in there before already, it was just not re-used between the diagram. So I briefly discussed with @kostrzewa after the group meeting. If I just clear that part of the QQ-cache, we should be back to where we started, right? I will implement this now as it might help me on JUWELS without changing the code too much.

**Comment by martin-ueding** [comment]
The change of the parallelization direction has also solved this problem.
